# Site settings
title: Tiffany Yu
email: tiffanyayu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/project-gh-pages"
url: "http://imtiffanyyu.github.io"
twitter_username: imtiffanyyu
github_username:  imtiffanyyu
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
